# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('topics', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='TopicQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_of', models.IntegerField()),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
            ],
            options={
                'verbose_name_plural': 'Topic Quizzes',
            },
        ),
        migrations.AlterModelOptions(
            name='subtopicquiz',
            options={'verbose_name_plural': 'Subtopic Quizzes'},
        ),
    ]
