# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170613_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.SubtopicQuiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.TopicQuiz'),
        ),
    ]
