# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170613_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz_subtopic',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_subtopic',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.SubtopicQuiz'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz_topic',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_topic',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.TopicQuiz'),
        ),
    ]
