# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('quiz', '0006_auto_20170613_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz_subtopic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz_topic',
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.ManyToManyField(to='topics.Subtopic'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='result',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
