# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20170613_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
    ]
