# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20170613_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_instances',
            field=models.BooleanField(default=False),
        ),
    ]
