# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
