# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20170613_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='multiple_instances',
        ),
        migrations.AddField(
            model_name='question',
            name='instances',
            field=models.IntegerField(default=1),
        ),
    ]
