# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_subtopic_is_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='is_real',
            field=models.BooleanField(default=False),
        ),
    ]
